### ISSUE TITLE
some files (especially photos) seem to shift the saturation / hue when saving with the pngquant plugin

### ISSUE THREAD

**Issue by mgrn0** [kornelski/pngquant-photoshop#2]
I recognized that some files, especially photo-like images seem to be a bit off regarding saturation and/or hue when being saved through the pngquant plugin.

I saved a photo through the old "save for web" - way and through pngquant to compare them, they look as following:
![screenshot](https://f.cloud.github.com/assets/3019226/1882470/91f419b8-7976-11e3-95ab-8792d7cfc529.jpg)
(save for web above, pngquant below).

In order to reproduce the case I uploaded the files here for download:
"original": https://dl.dropboxusercontent.com/u/81358/temp/2013-08-31-11.19.52.jpg
"pngquant result": https://dl.dropboxusercontent.com/u/81358/temp/2013-08-31-11.19.52-libquant.png
"save for web result": https://dl.dropboxusercontent.com/u/81358/temp/2013-08-31-11.19.52.png

**Comment by kornelski** [comment]
Sorry, I can't fix it, as this is a bug in Preview.app and QuickLook in Mac OS X Mavericks. Apple has confirmed it as bug rdar://15303483

You can urge Apple to fix their PNG support at https://bugreport.apple.com/‎

**Comment by mgrn0** [comment]
Thanks for the information, good to know it is just a Preview bug.
