### ISSUE TITLE
Should this work on 10.6.8 in Photoshop CS5?

### ISSUE THREAD

**Issue by azav** [kornelski/pngquant-photoshop#3]
After installing the plugin, launching PS CS5, opening an image and doing a Save As, the indicated option is not in the drop down menu.

The console does not display any messages different from a standard PS start up process.

**Comment by kornelski** [comment]
I've had feedback that it works in CS5 as well.

The plug-in is compiled for 64-bit only though. Is your Photoshop running in 64-bit mode? (you can check "Kind" column in Activity Monitor).

**Comment by azav** [comment]
Yes, it is certainly running in 64 bit.

If I get some time, I'll download the source and try a build myself to see if that makes any difference.

I look forward to seeing this in action.  

Cheers

**Comment by kornelski** [comment]
Please try SuperPNG - http://fnordware.com/superpng/ it uses pngquant, but has better compatibility.
