### ISSUE TITLE
Add preview

### ISSUE THREAD

**Issue by strarsis** [kornelski/pngquant-photoshop#6]
It would be great to see a preview of the image with the settings applies 
(including settings proposed here: https://github.com/pornel/pngquant-photoshop/issues/4).
Instant feedback and avoiding the 'min' parameter (as the CLI requires) is something a GUI could offer.

**Comment by kornelski** [comment]
Sorry, I won't add it. Photoshop SDK is hard to work with, so I'm unlikely to extend this code.
